// TestTypeDiscoveryService.cpp
// Unit tests for TypeDiscoveryService (V2)
//
// Tests type-list loading from types.json generated by DiaCLI.

#include <gtest/gtest.h>
#include <DiaApplicationEditor/V2/TypeDiscoveryService.h>
#include <DiaCore/CRC/StringCRC.h>

#include <stdio.h>
#include <string.h>

using namespace Dia::ApplicationFlow::Editor;
using Dia::Core::StringCRC;

// ==============================================================================
// Test Helpers
// ==============================================================================

static void WriteTypesJson(const char* path, const char* content)
{
    FILE* f = nullptr;
    fopen_s(&f, path, "w");
    if (f) { fputs(content, f); fclose(f); }
}

static void DeleteFile(const char* path)
{
    remove(path);
}

static const char* kTestJsonPath = "TestTypeDiscovery_types.json";

static const char* kValidTwoModulesOnePU =
    "{"
    "  \"generated\": \"2026-05-19T10:30:00Z\","
    "  \"modules\": ["
    "    { \"type_id\": \"KernelModule\",  \"description\": \"Window and input management\" },"
    "    { \"type_id\": \"RenderModule\",  \"description\": \"Rendering subsystem\" }"
    "  ],"
    "  \"processing_units\": ["
    "    { \"type_id\": \"ProcessingUnit\", \"description\": \"Default PU type\" }"
    "  ]"
    "}";

static const char* kValidOneModuleNoPU =
    "{"
    "  \"modules\": ["
    "    { \"type_id\": \"KernelModule\", \"description\": \"Window and input management\" }"
    "  ],"
    "  \"processing_units\": []"
    "}";

static const char* kValidNoModulesOnePU =
    "{"
    "  \"modules\": [],"
    "  \"processing_units\": ["
    "    { \"type_id\": \"ProcessingUnit\", \"description\": \"Default PU type\" }"
    "  ]"
    "}";

static const char* kValidDescriptionJson =
    "{"
    "  \"modules\": ["
    "    { \"type_id\": \"LoggingModule\", \"description\": \"Log subsystem\" }"
    "  ],"
    "  \"processing_units\": []"
    "}";

static const char* kValidJsonB =
    "{"
    "  \"modules\": ["
    "    { \"type_id\": \"AudioModule\", \"description\": \"Audio subsystem\" }"
    "  ],"
    "  \"processing_units\": []"
    "}";

// ==============================================================================
// Tests
// ==============================================================================

TEST(TypeDiscoveryService, DefaultConstruct_IsNotLoaded)
{
    TypeDiscoveryService service;
    EXPECT_FALSE(service.IsLoaded());
}

TEST(TypeDiscoveryService, LoadFromFile_ValidJson_IsLoaded)
{
    WriteTypesJson(kTestJsonPath, kValidTwoModulesOnePU);

    TypeDiscoveryService service;
    service.LoadFromFile(kTestJsonPath);
    EXPECT_TRUE(service.IsLoaded());

    DeleteFile(kTestJsonPath);
}

TEST(TypeDiscoveryService, LoadFromFile_ModuleCount_Matches)
{
    WriteTypesJson(kTestJsonPath, kValidTwoModulesOnePU);

    TypeDiscoveryService service;
    service.LoadFromFile(kTestJsonPath);
    EXPECT_EQ(service.GetModuleTypeCount(), 2u);

    DeleteFile(kTestJsonPath);
}

TEST(TypeDiscoveryService, LoadFromFile_PUCount_Matches)
{
    WriteTypesJson(kTestJsonPath, kValidNoModulesOnePU);

    TypeDiscoveryService service;
    service.LoadFromFile(kTestJsonPath);
    EXPECT_EQ(service.GetPUTypeCount(), 1u);

    DeleteFile(kTestJsonPath);
}

TEST(TypeDiscoveryService, LoadFromFile_ModuleTypeId_Correct)
{
    WriteTypesJson(kTestJsonPath, kValidOneModuleNoPU);

    TypeDiscoveryService service;
    service.LoadFromFile(kTestJsonPath);
    EXPECT_TRUE(service.IsKnownModuleType(StringCRC("KernelModule")));

    DeleteFile(kTestJsonPath);
}

TEST(TypeDiscoveryService, LoadFromFile_UnknownModule_ReturnsFalse)
{
    WriteTypesJson(kTestJsonPath, kValidOneModuleNoPU);

    TypeDiscoveryService service;
    service.LoadFromFile(kTestJsonPath);
    EXPECT_FALSE(service.IsKnownModuleType(StringCRC("Bogus")));

    DeleteFile(kTestJsonPath);
}

TEST(TypeDiscoveryService, LoadFromFile_ModuleDescription_Preserved)
{
    WriteTypesJson(kTestJsonPath, kValidDescriptionJson);

    TypeDiscoveryService service;
    service.LoadFromFile(kTestJsonPath);

    ASSERT_EQ(service.GetModuleTypeCount(), 1u);
    const TypeDiscoveryService::TypeInfo* types = service.GetModuleTypes();
    ASSERT_NE(types, nullptr);
    EXPECT_STREQ(types[0].description, "Log subsystem");

    DeleteFile(kTestJsonPath);
}

TEST(TypeDiscoveryService, LoadFromFile_MissingFile_DoesNotCrash)
{
    TypeDiscoveryService service;
    service.LoadFromFile("nonexistent_path_that_does_not_exist_12345.json");
    EXPECT_FALSE(service.IsLoaded());
}

TEST(TypeDiscoveryService, LoadFromFile_MalformedJson_DoesNotCrash)
{
    WriteTypesJson(kTestJsonPath, "{not valid json");

    TypeDiscoveryService service;
    service.LoadFromFile(kTestJsonPath);
    EXPECT_FALSE(service.IsLoaded());

    DeleteFile(kTestJsonPath);
}

TEST(TypeDiscoveryService, Clear_AfterLoad_NotLoaded)
{
    WriteTypesJson(kTestJsonPath, kValidOneModuleNoPU);

    TypeDiscoveryService service;
    service.LoadFromFile(kTestJsonPath);
    ASSERT_TRUE(service.IsLoaded());

    service.Clear();
    EXPECT_FALSE(service.IsLoaded());

    DeleteFile(kTestJsonPath);
}

TEST(TypeDiscoveryService, Refresh_ReloadsData)
{
    const char* pathA = "TestTypeDiscovery_A.json";
    const char* pathB = "TestTypeDiscovery_B.json";

    // Load A: one module "KernelModule"
    WriteTypesJson(pathA, kValidOneModuleNoPU);
    // Load B: one module "AudioModule"
    WriteTypesJson(pathB, kValidJsonB);

    TypeDiscoveryService service;
    service.LoadFromFile(pathA);
    ASSERT_TRUE(service.IsKnownModuleType(StringCRC("KernelModule")));

    service.Refresh(pathB);
    EXPECT_FALSE(service.IsKnownModuleType(StringCRC("KernelModule")));
    EXPECT_TRUE(service.IsKnownModuleType(StringCRC("AudioModule")));

    DeleteFile(pathA);
    DeleteFile(pathB);
}
