"""dia docs capabilities — generate engine-capabilities.md from system spec tags."""
from __future__ import annotations

import re
from datetime import date
from pathlib import Path
from typing import Dict, List

import click

from dia_cli.utils.repo_root import find_repo_root


_SPEC_STATUS_RE = re.compile(r'\*\*Status:\*\*\s*`?(\w[\w ]*?)`?\s*$', re.MULTILINE)
_DOMAINS_RE = re.compile(r'\*\*Gameplay Domains:\*\*\s*(.+)$', re.MULTILINE)

_VALID_DOMAINS = {
    "movement", "physics", "collision", "animation", "rendering",
    "lighting", "camera", "ai", "pathfinding", "input", "audio",
    "ui", "scene", "persistence", "debug",
}

_DOMAIN_ORDER = [
    "movement", "physics", "collision", "animation", "rendering",
    "lighting", "camera", "ai", "pathfinding", "input", "audio",
    "ui", "scene", "persistence", "debug",
]

_DOMAIN_LABELS = {
    "ai": "AI",
    "ui": "UI",
}


def _domain_label(domain: str) -> str:
    return _DOMAIN_LABELS.get(domain, domain.title())

_STATUS_ICON = {
    "Done": "✅",
    "In Progress": "🔨",
    "Approved": "📋",
    "Draft": "📝",
}


def _spec_status(text: str) -> str:
    m = _SPEC_STATUS_RE.search(text)
    return m.group(1).strip() if m else "Unknown"


def _spec_domains(text: str) -> List[str]:
    m = _DOMAINS_RE.search(text)
    if not m:
        return []
    raw = m.group(1).strip().rstrip(".")
    return [d.strip().lower() for d in raw.split(",") if d.strip()]


def _collect_system_specs(specs_dir: Path) -> List[Path]:
    result = []
    for md in specs_dir.rglob("*.md"):
        if "." in md.stem:
            continue
        if md.parent.name == md.stem:
            result.append(md)
    return sorted(result)


def _spec_rel_link(spec_path: Path, repo_root: Path) -> str:
    """Return a repo-root-relative path string suitable for markdown links."""
    return spec_path.relative_to(repo_root).as_posix()


def generate_capabilities(repo_root: Path, verbose: bool = False) -> tuple[str, list[str]]:
    """Scan all system specs and build a domain-grouped capability view.

    Returns (markdown_content, validation_warnings).
    """
    specs_dir = repo_root / "docs" / "specs" / "applications"
    specs = _collect_system_specs(specs_dir)

    # domain -> list of (name, status, rel_path)
    domain_map: Dict[str, list] = {d: [] for d in _DOMAIN_ORDER}
    untagged: list = []
    warnings: list[str] = []
    tagged_count = 0

    for spec_path in specs:
        if verbose:
            click.echo(f"  {spec_path.relative_to(repo_root)}")
        try:
            text = spec_path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue

        name = spec_path.stem
        status = _spec_status(text)
        domains = _spec_domains(text)
        rel = _spec_rel_link(spec_path, repo_root)

        invalid = [d for d in domains if d not in _VALID_DOMAINS]
        for inv in invalid:
            warnings.append(
                f"{spec_path.relative_to(repo_root)}: unknown domain '{inv}' "
                f"(see docs/reference/gameplay-domains.md)"
            )

        valid_domains = [d for d in domains if d in _VALID_DOMAINS]

        if valid_domains:
            tagged_count += 1
            for d in valid_domains:
                domain_map[d].append((name, status, rel))
        else:
            untagged.append((name, status, rel))

    # Render
    icon_legend = " | ".join(f"{v} {k}" for k, v in _STATUS_ICON.items())
    lines = [
        "# Engine Capabilities",
        "",
        "_Auto-generated by `dia docs capabilities`. Do not edit manually._",
        f"_Tag a system spec with `**Gameplay Domains:** movement, physics` to appear here._",
        "",
        f"**Last Updated:** {date.today().isoformat()}  ",
        f"**Systems tagged:** {tagged_count} / {tagged_count + len(untagged)}  ",
        f"**Legend:** {icon_legend}",
        "",
        "---",
        "",
    ]

    for domain in _DOMAIN_ORDER:
        entries = domain_map[domain]
        if not entries:
            continue
        lines += [
            f"## {_domain_label(domain)}",
            "",
            "| System | Status | Spec |",
            "|--------|--------|------|",
        ]
        for name, status, rel in sorted(entries, key=lambda e: e[0].lower()):
            icon = _STATUS_ICON.get(status, "❓")
            lines.append(f"| {name} | {icon} {status} | [{name}]({rel}) |")
        lines.append("")

    # Domains with no tagged specs
    empty_domains = [d for d in _DOMAIN_ORDER if not domain_map[d]]
    if empty_domains:
        lines += [
            "---",
            "",
            "## Untagged Domains",
            "",
            "No system specs are tagged for these domains yet:",
            "",
        ]
        for d in empty_domains:
            lines.append(f"- `{d}`")
        lines.append("")

    # Untagged specs
    if untagged:
        lines += [
            "---",
            "",
            f"## Untagged Systems ({len(untagged)})",
            "",
            "_These specs have no `**Gameplay Domains:**` field. Add one to include them above._",
            "",
            "| System | Status |",
            "|--------|--------|",
        ]
        for name, status, _ in sorted(untagged, key=lambda e: e[0].lower()):
            icon = _STATUS_ICON.get(status, "❓")
            lines.append(f"| {name} | {icon} {status} |")
        lines.append("")

    return "\n".join(lines), warnings


@click.command("capabilities")
@click.option("--dry-run", is_flag=True, default=False,
              help="Print to stdout instead of writing file.")
@click.option("--verbose", is_flag=True, default=False,
              help="Print each spec being processed.")
def capabilities(dry_run: bool, verbose: bool) -> None:
    """Generate docs/reference/engine-capabilities.md from system spec tags.

    Reads **Gameplay Domains:** fields from system specs and groups them
    into a single capability view. Specs without the field appear in an
    Untagged section at the bottom.

    Add the field to a system spec like:
        **Gameplay Domains:** movement, physics

    Valid domain values are listed in docs/reference/gameplay-domains.md.
    """
    repo_root = find_repo_root(__file__)

    click.echo("[dia docs] Scanning system specs for Gameplay Domains tags...")
    content, warnings = generate_capabilities(repo_root, verbose=verbose)

    if warnings:
        click.echo(f"[dia docs] {len(warnings)} domain warning(s):", err=True)
        for w in warnings:
            click.echo(f"  ⚠  {w}", err=True)

    if dry_run:
        click.echo(content)
        return

    out_path = repo_root / "docs" / "reference" / "engine-capabilities.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    click.echo(
        f"[dia docs] Wrote {out_path.relative_to(repo_root)} "
        f"({content.count(chr(10))} lines)"
    )
