"""dia docs registry — auto-generate module-registry.md from module YAML files."""
from __future__ import annotations

import re
from datetime import date
from pathlib import Path
from typing import Dict, List, Optional

import click

from dia_cli.utils.repo_root import find_repo_root


def _parse_frontmatter(text: str) -> dict:
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}

    end = -1
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            end = i
            break
    if end == -1:
        return {}

    fm_lines = lines[1:end]
    result: dict = {"dependent_modules": [], "responsibilities": [], "public_api": {}}

    in_list_field: Optional[str] = None
    for line in fm_lines:
        stripped = line.rstrip()

        if re.match(r"^\w", stripped) and ":" in stripped:
            in_list_field = None

        for field in ("module_id", "name", "layer", "status", "maturity", "path",
                      "parent_module_id", "summary", "intent", "language", "schema"):
            if stripped.startswith(f"{field}:"):
                val = stripped.split(":", 1)[1].strip().strip('"').strip("'")
                result[field] = val
                break
        else:
            if stripped.startswith("dependent_modules:"):
                rest = stripped.split(":", 1)[1].strip()
                if rest == "[]":
                    result["dependent_modules"] = []
                in_list_field = "dependent_modules"
            elif stripped.startswith("responsibilities:"):
                in_list_field = "responsibilities"
            elif in_list_field and stripped.startswith("  - "):
                item = stripped[4:].strip().strip('"').strip("'")
                result.setdefault(in_list_field, []).append(item)

    return result


def _build_tree(modules: List[dict]) -> Dict[str, List[dict]]:
    tree: Dict[str, List[dict]] = {}
    for mod in modules:
        parent = mod.get("parent_module_id", "")
        tree.setdefault(parent, []).append(mod)
    for children in tree.values():
        children.sort(key=lambda m: m.get("module_id", ""))
    return tree


def _render_module(mod: dict, depth: int) -> str:
    indent = "  " * depth
    mid = mod.get("module_id", "?")
    name = mod.get("name", "?")
    layer = mod.get("layer", "?")
    status = mod.get("status", "?")
    path = mod.get("path", "?")
    summary = mod.get("summary", "")

    line = f"{indent}- **{mid}** ({name}) — `{path}` [{layer}/{status}]"
    if summary and summary != "TODO: describe this module":
        line += f"\n{indent}  {summary}"
    return line


def _render_tree(tree: Dict[str, List[dict]], parent_id: str, depth: int) -> List[str]:
    lines: List[str] = []
    children = tree.get(parent_id, [])
    for mod in children:
        lines.append(_render_module(mod, depth))
        mid = mod.get("module_id", "")
        if mid in tree:
            lines.extend(_render_tree(tree, mid, depth + 1))
    return lines


def generate_registry(repo_root: Path) -> str:
    module_files = sorted(
        f for f in repo_root.rglob("dia.*.architecture.module.md")
        if ".claude" not in str(f) and "node_modules" not in str(f)
    )

    modules: List[dict] = []
    for mf in module_files:
        fm = _parse_frontmatter(mf.read_text(encoding="utf-8", errors="ignore"))
        if fm.get("module_id"):
            fm["_file"] = str(mf.relative_to(repo_root))
            modules.append(fm)

    tree = _build_tree(modules)

    roots = [m for m in modules if not m.get("parent_module_id")]
    roots.sort(key=lambda m: m.get("module_id", ""))

    output_lines = [
        "# Module Registry",
        "",
        f"**Last Updated:** {date.today().isoformat()}",
        f"**Total Modules:** {len(modules)}",
        "",
        "> Auto-generated by `dia docs registry`. Do not edit manually.",
        "",
        "---",
        "",
        "## Layer Summary",
        "",
        "| Layer | Count |",
        "|-------|-------|",
    ]

    top_layers: Dict[str, int] = {}
    for mod in modules:
        layer = mod.get("layer", "unknown")
        top = layer.split("/")[0] if "/" in layer else layer
        top_layers[top] = top_layers.get(top, 0) + 1

    for layer in sorted(top_layers.keys()):
        output_lines.append(f"| {layer} | {top_layers[layer]} |")

    output_lines.extend(["", "---", "", "## Module Hierarchy", ""])

    for root in roots:
        rid = root.get("module_id", "")
        output_lines.extend(_render_tree(tree, root.get("parent_module_id", ""), 0))
        output_lines.append("")

    if not roots:
        for parent_id in sorted(tree.keys()):
            if parent_id and parent_id not in {m.get("module_id") for m in modules}:
                output_lines.append(f"### Under {parent_id} (parent not found)")
                output_lines.extend(_render_tree(tree, parent_id, 0))
                output_lines.append("")

    return "\n".join(output_lines) + "\n"


@click.command("registry")
@click.option("--dry-run", is_flag=True, default=False, help="Print to stdout instead of writing file.")
def registry(dry_run: bool) -> None:
    """Regenerate docs/reference/registry/module-registry.md from module YAML files.

    Scans all dia.*.architecture.module.md files, extracts frontmatter,
    and produces a read-only registry document.
    """
    repo_root = find_repo_root(__file__)
    content = generate_registry(repo_root)

    if dry_run:
        click.echo(content)
        return

    out_path = repo_root / "docs" / "reference" / "registry" / "module-registry.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    click.echo(f"[dia docs] Wrote {out_path.relative_to(repo_root)} ({content.count(chr(10))} lines)")
