#pragma once

#include <DiaCore/Containers/Arrays/DynamicArrayC.h>
#include <DiaCore/CRC/StringCRC.h>

namespace Dia
{
    namespace ApplicationFlow
    {
        namespace Editor
        {
            // Reads a registeredtypes.diaschema file generated by DiaCLI and provides the list of
            // registered module and processing unit types for autocomplete in the editor.
            //
            // Static mode: reads types.json from the file system.
            // Live mode: would query TypeRegistry via DiaAPI (interface hook provided; not yet wired).
            class TypeDiscoveryService
            {
            public:
                struct TypeInfo
                {
                    Dia::Core::StringCRC typeId;
                    char                 description[128];
                };

                static constexpr unsigned int kMaxModuleTypes = 64;
                static constexpr unsigned int kMaxPUTypes     = 16;

                TypeDiscoveryService() = default;

                // Load type data from a types.json file on disk.
                // On error (file not found, malformed JSON) the service is cleared silently.
                void LoadFromFile(const char* typesJsonPath);

                // Load type data directly from the in-process TypeRegistry.
                // Descriptions come from DIA_DESCRIBE registrations.
                // Only populates module types; PU types are not in TypeRegistry.
                void LoadFromRegistry();

                // Reset the service to an empty, unloaded state.
                void Clear();

                // Re-read from the same path: equivalent to Clear() + LoadFromFile(path).
                void Refresh(const char* typesJsonPath);

                // Accessors
                unsigned int    GetModuleTypeCount() const;
                const TypeInfo* GetModuleTypes()     const;
                unsigned int    GetPUTypeCount()     const;
                const TypeInfo* GetPUTypes()         const;

                // Lookup
                bool IsKnownModuleType(Dia::Core::StringCRC typeId) const;
                bool IsKnownPUType(Dia::Core::StringCRC typeId)     const;

                // True if at least one type entry has been loaded.
                bool IsLoaded() const;

            private:
                Dia::Core::Containers::DynamicArrayC<TypeInfo, kMaxModuleTypes> mModuleTypes;
                Dia::Core::Containers::DynamicArrayC<TypeInfo, kMaxPUTypes>     mPUTypes;
            };

        } // namespace Editor
    } // namespace ApplicationFlow
} // namespace Dia
